homepage:
    path:     /
    defaults: { _controller: WerkstattFootBundle:Foot:index}


werkstatt_foot:
    resource: "@WerkstattFootBundle/Controller/"
    type:     annotation
    prefix:   /foot


MopaBootstrapSandbox:
    resource: "@MopaBootstrapSandboxBundle/Resources/config/routing.yml"