<?php

namespace Werkstatt\Bundle\FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends EntityRepository
{
}
